project:
  type: website
  output-dir: docs

website:
  title: "Kyle Rohn - Quarto Demo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: hobbies.qmd
        text: Hobbies

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



